
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserProfileScalarFieldEnum = {
  id: 'id',
  username: 'username',
  passwordHash: 'passwordHash',
  email: 'email',
  status: 'status',
  scope: 'scope',
  tgId: 'tgId',
  createdAt: 'createdAt'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  priority: 'priority',
  description: 'description',
  scope: 'scope',
  campaignId: 'campaignId',
  teamId: 'teamId'
};

exports.Prisma.RoleAccessScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  accessProfileId: 'accessProfileId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SystemUserScalarFieldEnum = {
  id: 'id',
  userProfileId: 'userProfileId',
  roleId: 'roleId',
  createdAt: 'createdAt'
};

exports.Prisma.CampaignUserScalarFieldEnum = {
  id: 'id',
  userProfileId: 'userProfileId',
  campaignId: 'campaignId',
  roleId: 'roleId',
  createdAt: 'createdAt'
};

exports.Prisma.TeamUserScalarFieldEnum = {
  id: 'id',
  userProfileId: 'userProfileId',
  teamId: 'teamId',
  roleId: 'roleId',
  createdAt: 'createdAt'
};

exports.Prisma.AdminScalarFieldEnum = {
  id: 'id',
  username: 'username',
  passwordHash: 'passwordHash',
  createdAt: 'createdAt'
};

exports.Prisma.CampaignScalarFieldEnum = {
  id: 'id',
  name: 'name',
  legalOwnerId: 'legalOwnerId',
  createdAt: 'createdAt'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  campaignId: 'campaignId',
  teamLeadId: 'teamLeadId',
  sharePwaWithinTeam: 'sharePwaWithinTeam',
  createdAt: 'createdAt'
};

exports.Prisma.DomainScalarFieldEnum = {
  id: 'id',
  hostname: 'hostname',
  status: 'status',
  pwaAppId: 'pwaAppId',
  ownerId: 'ownerId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PixelTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  description: 'description',
  ownerId: 'ownerId',
  campaignId: 'campaignId',
  teamId: 'teamId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PwaAppScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  campaignId: 'campaignId',
  teamId: 'teamId',
  pixelTokenId: 'pixelTokenId',
  domainId: 'domainId',
  isDeleted: 'isDeleted',
  mainLocale: 'mainLocale',
  destinationUrl: 'destinationUrl',
  productUrl: 'productUrl',
  author: 'author',
  rating: 'rating',
  adsText: 'adsText',
  category: 'category',
  categorySubtitle: 'categorySubtitle',
  installCount: 'installCount',
  installCountLabel: 'installCountLabel',
  reviewsCount: 'reviewsCount',
  reviewsCountLabel: 'reviewsCountLabel',
  appSize: 'appSize',
  appSizeLabel: 'appSizeLabel',
  ageLimit: 'ageLimit',
  ageLimitLabel: 'ageLimitLabel',
  iconUrl: 'iconUrl',
  galleryUrls: 'galleryUrls',
  createdByCampaignUserId: 'createdByCampaignUserId',
  createdByTeamUserId: 'createdByTeamUserId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PwaDetailsScalarFieldEnum = {
  id: 'id',
  pwaAppId: 'pwaAppId',
  publicName: 'publicName',
  iconUrl: 'iconUrl',
  logoUrl: 'logoUrl',
  themeColor: 'themeColor',
  screenshots: 'screenshots'
};

exports.Prisma.PwaContentScalarFieldEnum = {
  id: 'id',
  pwaAppId: 'pwaAppId',
  locale: 'locale',
  title: 'title',
  description: 'description'
};

exports.Prisma.PwaTagScalarFieldEnum = {
  id: 'id',
  text: 'text',
  pwaAppId: 'pwaAppId'
};

exports.Prisma.PwaTermScalarFieldEnum = {
  id: 'id',
  text: 'text',
  pwaAppId: 'pwaAppId'
};

exports.Prisma.PwaCommentScalarFieldEnum = {
  id: 'id',
  author: 'author',
  text: 'text',
  pwaAppId: 'pwaAppId'
};

exports.Prisma.PwaEventsProfileScalarFieldEnum = {
  id: 'id',
  pwaAppId: 'pwaAppId',
  viewContent: 'viewContent',
  firstOpen: 'firstOpen',
  reg: 'reg',
  sub: 'sub',
  dep: 'dep',
  redep: 'redep'
};

exports.Prisma.PwaEventsConfigScalarFieldEnum = {
  id: 'id',
  pwaAppId: 'pwaAppId',
  eventType: 'eventType',
  destination: 'destination'
};

exports.Prisma.PwaVersionScalarFieldEnum = {
  id: 'id',
  pwaAppId: 'pwaAppId',
  versionNumber: 'versionNumber',
  changedBy: 'changedBy',
  createdAt: 'createdAt'
};

exports.Prisma.FlowScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  campaignId: 'campaignId',
  teamId: 'teamId',
  createdByCampaignUserId: 'createdByCampaignUserId',
  createdByTeamUserId: 'createdByTeamUserId',
  pwaAppId: 'pwaAppId',
  activeVersionId: 'activeVersionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FlowVersionScalarFieldEnum = {
  id: 'id',
  flowId: 'flowId',
  versionNumber: 'versionNumber',
  status: 'status',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
};

exports.Prisma.PwaSessionScalarFieldEnum = {
  id: 'id',
  pixelId: 'pixelId',
  pwaAppId: 'pwaAppId',
  campaignId: 'campaignId',
  teamId: 'teamId',
  ownerUserId: 'ownerUserId',
  queryStringRaw: 'queryStringRaw',
  viewContentLogId: 'viewContentLogId',
  leadEventLogId: 'leadEventLogId',
  regEventLogId: 'regEventLogId',
  subEventLogId: 'subEventLogId',
  firstDepEventLogId: 'firstDepEventLogId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SessionDepositScalarFieldEnum = {
  id: 'id',
  eventLogId: 'eventLogId',
  amount: 'amount',
  depositedAt: 'depositedAt',
  createdAt: 'createdAt'
};

exports.Prisma.EventLogScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  pixelId: 'pixelId',
  campaignId: 'campaignId',
  teamId: 'teamId',
  ownerUserId: 'ownerUserId',
  pwaAppId: 'pwaAppId',
  flowId: 'flowId',
  eventType: 'eventType',
  eventId: 'eventId',
  status: 'status',
  installId: 'installId',
  fbclid: 'fbclid',
  rawQuery: 'rawQuery',
  regionId: 'regionId',
  countryId: 'countryId',
  os: 'os',
  deviceType: 'deviceType',
  browser: 'browser',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  language: 'language',
  domainId: 'domainId',
  isWhitepage: 'isWhitepage',
  responseData: 'responseData',
  createdAt: 'createdAt'
};

exports.Prisma.CountryScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.RegionScalarFieldEnum = {
  id: 'id',
  countryId: 'countryId',
  name: 'name',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.WorkingObjectScalarFieldEnum = {
  id: 'id',
  type: 'type',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkingObjectPwaScalarFieldEnum = {
  workingObjectId: 'workingObjectId',
  pwaAppId: 'pwaAppId'
};

exports.Prisma.WorkingObjectFlowScalarFieldEnum = {
  workingObjectId: 'workingObjectId',
  flowId: 'flowId'
};

exports.Prisma.WorkingObjectPixelTokenScalarFieldEnum = {
  workingObjectId: 'workingObjectId',
  pixelTokenId: 'pixelTokenId'
};

exports.Prisma.WorkingObjectCampaignScalarFieldEnum = {
  workingObjectId: 'workingObjectId',
  campaignId: 'campaignId'
};

exports.Prisma.WorkingObjectTeamScalarFieldEnum = {
  workingObjectId: 'workingObjectId',
  teamId: 'teamId',
  createdAt: 'createdAt'
};

exports.Prisma.WorkingObjectTeamUserScalarFieldEnum = {
  workingObjectId: 'workingObjectId',
  teamUserId: 'teamUserId',
  relation: 'relation',
  createdAt: 'createdAt'
};

exports.Prisma.ShareRoleScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  workingObjectId: 'workingObjectId',
  accessProfileId: 'accessProfileId',
  createdByCampaignUserId: 'createdByCampaignUserId',
  createdByTeamUserId: 'createdByTeamUserId',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.ShareUserProfileScalarFieldEnum = {
  id: 'id',
  userProfileId: 'userProfileId',
  workingObjectId: 'workingObjectId',
  accessProfileId: 'accessProfileId',
  createdBy: 'createdBy',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.GlobalAccessRulesScalarFieldEnum = {
  id: 'id',
  statAccess: 'statAccess',
  finAccess: 'finAccess',
  logAccess: 'logAccess',
  usersAccess: 'usersAccess',
  sharingAccess: 'sharingAccess',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CrudAccessRulesScalarFieldEnum = {
  id: 'id',
  read: 'read',
  update: 'update',
  delete: 'delete',
  create: 'create',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccessProfileScalarFieldEnum = {
  id: 'id',
  name: 'name',
  globalRulesId: 'globalRulesId',
  crudRulesId: 'crudRulesId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GlobalAccessUserScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  accessProfileId: 'accessProfileId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  campaignId: 'campaignId',
  userId: 'userId',
  title: 'title',
  status: 'status',
  priority: 'priority',
  dueDate: 'dueDate',
  createdAt: 'createdAt'
};

exports.Prisma.ErrorLogScalarFieldEnum = {
  id: 'id',
  level: 'level',
  message: 'message',
  stack: 'stack',
  service: 'service',
  userId: 'userId',
  sessionId: 'sessionId',
  createdAt: 'createdAt'
};

exports.Prisma.FinancialScalarFieldEnum = {
  id: 'id',
  campaignId: 'campaignId',
  spend: 'spend',
  payouts: 'payouts',
  profit: 'profit',
  transactionDate: 'transactionDate'
};

exports.Prisma.AlertScalarFieldEnum = {
  id: 'id',
  campaignId: 'campaignId',
  type: 'type',
  message: 'message',
  severity: 'severity',
  isResolved: 'isResolved',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Status = exports.$Enums.Status = {
  active: 'active',
  inactive: 'inactive'
};

exports.ScopeType = exports.$Enums.ScopeType = {
  SYSTEM: 'SYSTEM',
  CAMPAIGN: 'CAMPAIGN',
  TEAM: 'TEAM'
};

exports.PwaStatus = exports.$Enums.PwaStatus = {
  draft: 'draft',
  published: 'published',
  archived: 'archived'
};

exports.EventType = exports.$Enums.EventType = {
  ViewContent: 'ViewContent',
  PageView: 'PageView',
  Lead: 'Lead',
  CompleteRegistration: 'CompleteRegistration',
  Purchase: 'Purchase',
  Subscribe: 'Subscribe'
};

exports.FlowStatus = exports.$Enums.FlowStatus = {
  draft: 'draft',
  published: 'published',
  archived: 'archived'
};

exports.LogStatus = exports.$Enums.LogStatus = {
  success: 'success',
  error: 'error'
};

exports.DeviceOs = exports.$Enums.DeviceOs = {
  Linux: 'Linux',
  Windows: 'Windows',
  MacOS: 'MacOS',
  Android: 'Android',
  IOS: 'IOS'
};

exports.DeviceType = exports.$Enums.DeviceType = {
  mobile: 'mobile',
  desktop: 'desktop'
};

exports.WorkingObjectType = exports.$Enums.WorkingObjectType = {
  PWA: 'PWA',
  FLOW: 'FLOW',
  PIXEL_TOKEN: 'PIXEL_TOKEN',
  TEAM: 'TEAM',
  CAMPAIGN: 'CAMPAIGN'
};

exports.WorkingObjectUserRelation = exports.$Enums.WorkingObjectUserRelation = {
  Owner: 'Owner',
  Editor: 'Editor',
  Viewer: 'Viewer'
};

exports.AccessLevel = exports.$Enums.AccessLevel = {
  None: 'None',
  View: 'View',
  Edit: 'Edit',
  Manage: 'Manage'
};

exports.TaskStatus = exports.$Enums.TaskStatus = {
  open: 'open',
  in_progress: 'in_progress',
  closed: 'closed'
};

exports.ErrorLevel = exports.$Enums.ErrorLevel = {
  Anomaly: 'Anomaly',
  TechError: 'TechError',
  TokenExpirity: 'TokenExpirity',
  TrashholdReached: 'TrashholdReached',
  info: 'info',
  warn: 'warn',
  error: 'error',
  fatal: 'fatal'
};

exports.AlertType = exports.$Enums.AlertType = {
  info: 'info',
  warn: 'warn',
  error: 'error',
  fatal: 'fatal'
};

exports.Prisma.ModelName = {
  UserProfile: 'UserProfile',
  Role: 'Role',
  RoleAccess: 'RoleAccess',
  SystemUser: 'SystemUser',
  CampaignUser: 'CampaignUser',
  TeamUser: 'TeamUser',
  Admin: 'Admin',
  Campaign: 'Campaign',
  Team: 'Team',
  Domain: 'Domain',
  PixelToken: 'PixelToken',
  PwaApp: 'PwaApp',
  PwaDetails: 'PwaDetails',
  PwaContent: 'PwaContent',
  PwaTag: 'PwaTag',
  PwaTerm: 'PwaTerm',
  PwaComment: 'PwaComment',
  PwaEventsProfile: 'PwaEventsProfile',
  PwaEventsConfig: 'PwaEventsConfig',
  PwaVersion: 'PwaVersion',
  Flow: 'Flow',
  FlowVersion: 'FlowVersion',
  PwaSession: 'PwaSession',
  SessionDeposit: 'SessionDeposit',
  EventLog: 'EventLog',
  Country: 'Country',
  Region: 'Region',
  WorkingObject: 'WorkingObject',
  WorkingObjectPwa: 'WorkingObjectPwa',
  WorkingObjectFlow: 'WorkingObjectFlow',
  WorkingObjectPixelToken: 'WorkingObjectPixelToken',
  WorkingObjectCampaign: 'WorkingObjectCampaign',
  WorkingObjectTeam: 'WorkingObjectTeam',
  WorkingObjectTeamUser: 'WorkingObjectTeamUser',
  ShareRole: 'ShareRole',
  ShareUserProfile: 'ShareUserProfile',
  GlobalAccessRules: 'GlobalAccessRules',
  CrudAccessRules: 'CrudAccessRules',
  AccessProfile: 'AccessProfile',
  GlobalAccessUser: 'GlobalAccessUser',
  AuditLog: 'AuditLog',
  Task: 'Task',
  ErrorLog: 'ErrorLog',
  Financial: 'Financial',
  Alert: 'Alert'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
