FROM node:22-alpine

WORKDIR /workspace
RUN apk add --no-cache python3 make g++ libc6-compat bash

COPY ./pwa-event-handler/package*.json ./pwa-event-handler/
COPY ./pwa-prisma/package*.json       ./pwa-prisma/
COPY ./pwa-shared/package*.json       ./pwa-shared/
COPY ./pwa-protos/package*.json       ./pwa-protos/

WORKDIR /workspace/pwa-event-handler
RUN npm ci

WORKDIR /workspace/pwa-prisma
RUN npm ci

WORKDIR /workspace/pwa-shared
RUN npm ci

WORKDIR /workspace
COPY ./pwa-event-handler ./pwa-event-handler
COPY ./pwa-prisma       ./pwa-prisma
COPY ./pwa-shared       ./pwa-shared
COPY ./pwa-protos       ./pwa-protos

WORKDIR /workspace/pwa-prisma
RUN npx prisma generate --schema=./prisma/schema.prisma

WORKDIR /workspace/pwa-event-handler
RUN mkdir -p ./prisma \
 && cp ../pwa-prisma/prisma/schema.prisma ./prisma/schema.prisma \
 && npx prisma generate --schema=./prisma/schema.prisma

RUN mkdir -p ./protos \
 && cp -r ../pwa-protos/protos/* ./protos/

ENV NODE_ENV=test

CMD ["npm", "run", "test:ci"]
