FROM node:22-alpine AS base
WORKDIR /workspace
RUN apk add --no-cache python3 make g++ libc6-compat openssl postgresql-client

FROM base AS deps
WORKDIR /workspace

COPY ./pwa-auth-service/package*.json ./pwa-auth-service/
COPY ./pwa-prisma/package*.json      ./pwa-prisma/
COPY ./pwa-shared/package*.json      ./pwa-shared/
COPY ./pwa-protos/package*.json      ./pwa-protos/

WORKDIR /workspace/pwa-shared
RUN npm ci

WORKDIR /workspace/pwa-prisma
RUN npm ci

WORKDIR /workspace/pwa-auth-service
RUN npm install

FROM base AS test-runner
WORKDIR /workspace

# Без цього кроку npx не бачить ваші встановлені пакети і качає Prisma 7!
COPY --from=deps /workspace/pwa-auth-service/node_modules ./pwa-auth-service/node_modules
COPY --from=deps /workspace/pwa-prisma/node_modules       ./pwa-prisma/node_modules
COPY --from=deps /workspace/pwa-shared/node_modules       ./pwa-shared/node_modules

COPY ./pwa-auth-service ./pwa-auth-service
COPY ./pwa-prisma       ./pwa-prisma
COPY ./pwa-shared       ./pwa-shared
COPY ./pwa-protos       ./pwa-protos

WORKDIR /workspace/pwa-prisma

RUN ./node_modules/.bin/prisma generate --schema=./prisma/schema.prisma

WORKDIR /workspace/pwa-auth-service
RUN mkdir -p ./prisma \
 && cp ../pwa-prisma/prisma/schema.prisma ./prisma/schema.prisma \
 && ./node_modules/.bin/prisma generate --schema=./prisma/schema.prisma

RUN mkdir -p ./protos \
 && cp -r ../pwa-protos/protos/* ./protos/

ENV NODE_ENV=test

CMD ["npm", "run", "test:ci"]