export const PWA_EVENTS_QUEUE = process.env.PWA_EVENTS_QUEUE ?? 'EVENTS_QUEUE';
export const PWA_EVENTS_PREFIX = process.env.PWA_EVENTS_PREFIX ?? 'pwa';

export const BUILD_PWA_CHANNEL = "BUILD_PWA_CHANNEL";
export const CREATE_APP_EVENT = "CREATE_APP_EVENT";
export const BUILD_FINISHED_EVENT = "BUILD_FINISHED_EVENT";
export const DELETE_APP_EVENT = "DELETE_APP_EVENT";
export const DELETE_FINISHED_EVENT = "DELETE_FINISHED_EVENT";